sudo: required
services:
  - docker

# Building a container to test the client using Development Dockerfile.dev in Client directory
before_install:
  - docker build -t samay/client-test -f ./client/Dockerfile.dev ./client

# Overriding default command of Dockerfile.dev inside client directory
script:
  - docker run -e CI=true samay/client-test npm test

# Building Production version using Production version of Dockerfile
after_success:
  - docker build -t samay1993/multi-client ./client
  - docker build -t samay1993/multi-nginx ./nginx
  - docker build -t samay1993/multi-server ./server
  - docker build -t samay1993/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Command to login into docker using travis CI where DOCKER_PASSWORD and DOCKER_ID are the environment variables added in Travis CI

  - docker push samay1993/multi-client
  - docker push samay1993/multi-nginx
  - docker push samay1993/multi-server
  - docker push samay1993/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-132174339745"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY