apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service

spec:
  type: ClusterIP
  # ClusterIP means only pods inside the node is going to have access to this cluster of pods
  selector:
    component: web
    #selector is set as component: web because on client-deployment we have labeled the container as component: web
  ports:
    # exposing the ports in which client-cluster-ip-service is going to be available
    - port: 3000 
      targetPort: 3000 
      # above lines means to get access to port 3000 inside the container i.e target port
      # you have to go to at port 3000 in the service i.e port: 3000
      